version: '3.8'

services:
  db:
    build: ./mysql
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 33090:3306
    volumes:
    - cafe_data:/var/lib/mysql
    env_file:
      - ./mysql/db-variables.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./mysql/myadmin.env
    depends_on:
      - db
    ports:
      - 8000:80

  php:
    build: ./php
    depends_on:
    - db
    ports:
    - 8001:80
    volumes:
      - ./src:/var/www/html

volumes:
  cafe_data:
